version: '3.8'

services:

  adminapp-db:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: backend
    ports:
      - 5000:5000
    env_file: ./.env
    environment:
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - adminapp-db
    volumes:
      - ./backend:/usr/local/app
    command: npm run dev

  frontend:
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/local/app
    command: npm start

volumes:
  database-data:
