version: '3.5'

services:

  adminapp-medified-db:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminapp-medified-backend:
    build: 
      context: backend
      args:
        NODE_ENV: "development"
    ports:
      - 5000:5000
    env_file: ./.env
    depends_on:
      - adminapp-medified-db
    volumes:
     - ./backend:/usr/src/app
    command: npm run dev
    container_name: adminapp-medified-backend
    
  adminapp-medified-frontend:
    build: 
      context: frontend
      args:
        NODE_ENV: "development"
    ports:
      - 3000:3000
    depends_on:
      - adminapp-medified-backend
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    container_name: adminapp-medified-frontend

volumes:
  database-data:
