version: '3.7'

services:
  adminapp-medified-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=adminapp
    volumes:
      - database-data:/var/lib/postgresql/data

  adminapp-medified-backend:
    image: ohtumedified/adminapp-medified-backend:latest
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=adminapp-medified-db
    depends_on:
      - adminapp-medified-db
    command: npm start
    container_name: adminapp-medified-backend

  adminapp-medified-frontend:
    image: ohtumedified/adminapp-medified-frontend:latest
    depends_on:
      - adminapp-medified-backend
    container_name: adminapp-medified-frontend

volumes:
  database-data:

networks:
  default:
    external:
      name: ohtup