version: '3.8'

services:

  adminapp-backend:
    build: backend
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - NODE_ENV=development
    volumes:
     - ./backend:/usr/src/app
    command: npm run dev
    container_name: adminapp-backend
    
  adminapp-frontend:
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      - adminapp-backend
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    container_name: adminapp-frontend
