version: '3.8'

services:

  adminapp-medified-backend:
    build: 
      context: backend
      args:
        NODE_ENV: "development"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    volumes:
     - ./backend:/usr/src/app
    command: npm run dev
    container_name: adminapp-medified-backend
    
  adminapp-medified-frontend:
    build: 
      context: frontend
      args:
        NODE_ENV: "development"
    ports:
      - 3000:3000
    depends_on:
      - adminapp-medified-backend
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    container_name: adminapp-medified-frontend
