name: Cypress Tests

on:
  push:
    branches: [workflow_testing]
    paths-ignore:
      - 'README.md'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: npm ci
          start: npm start